### PR TITLE
ts-essentials can exist in devDependencies

### PR DESCRIPTION
**Pull request by dphrag**

### CODE REVIEW

**Comment by Methuselah96** [comment]
@Andarist Any thoughts about this PR? I'm now getting a warning in Yarn 2 after https://github.com/Andarist/use-composed-ref/pull/2 was released and it does seem like `ts-essentials` could be demoted to devDependency given its current usage.

➤ YN0002: │ use-composed-ref@npm:1.2.0 [044bc] doesn't provide typescript (p6ab00), requested by ts-essentials

**Comment by Andarist** [comment]
@Methuselah96 I would accept a PR that would inline that one type that is used from that package (and remove the dependency altogether)

**Comment by Methuselah96** [comment]
@Andarist https://github.com/Andarist/use-composed-ref/pull/5

**Comment by Andarist** [comment]
This got somewhat resolved by #5 and the new release is available on npm: v1.2.1

Sorry that I didn't get to this PR sooner

**Pull request closed without merging**
